[pytest]
testpaths = features
markers =
    proxy: requires proxy host
    sle_minion: requires sle_minion host
    skip: unconditionally skip
    skip_known_issue: known failure
    scope_cobbler: extra cobbler log on failure
    susemanager: SUSE Manager product only
    uyuni: Uyuni product only
    head: head version only
    cloud: cloud environment only
    skip_if_cloud: skip in cloud
    containerized_server: containerized server only
    skip_if_containerized_server: skip if containerized
    rke2: RKE2 only
    salt_bundle: salt bundle only
    skip_if_salt_bundle: skip if salt bundle
    beta: beta channels only
